-- generated by gemini 2.5 flash
return function()
	local orderedTable = {
		_data = {},
		_keys = {},
	}

	function orderedTable:insert(key, value)
		if self._data[key] == nil then
			table.insert(self._keys, key)
		end
		self._data[key] = value
	end

	function orderedTable:get(key)
		return self._data[key]
	end

	function orderedTable:remove(key)
		self._data[key] = nil

		for i, k in ipairs(self._keys) do
			if k == key then
				table.remove(self._keys, i)
				return
			end
		end
	end

	function orderedTable:orderedPairs()
		local i = 0
		local keys = self._keys
		local data = self._data

		return function()
			i = i + 1
			local key = keys[i]
			if key then
				return key, data[key]
			end
		end
	end

	return orderedTable
end
